### PR TITLE
added timeout in client call

### PR DESCRIPTION
**Pull request by pprolancer**
- added timeout in Client method call.
- fixed default redis_url to 'redis://'

### CODE REVIEW

**Comment by pprolancer** [comment]
@gowhari 
would you please check this pull request and merge that if is OK?
I really need to have a timeout in call method from client to avoid long blocking.
Thanks

**Comment by gowhari** [comment]
It's better to resolve different issues in separate commits, and with mote clear comments.

If timeout happens in client call, server response will remain in redis forever. We should also clear response key.

**Comment by gowhari** [comment]
@pprolancer I will add it today.

**Comment by pprolancer** [comment]
> If timeout happens in client call, server response will remain in redis forever. We should also clear response key.

yes, you're right.
I was added another change later to remove the key in Client class before raise timeout error.

**Comment by gowhari** [comment]
Implemented in 4871b22
You can install version 0.3.0 with pip to use it, it's already on pypi.

**Pull request closed without merging**
